name: Python Package using Conda
on: [push]

jobs:
  test:
    name: Test python ${{ matrix.python-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      #- name: install mamba
        #uses: mamba-org/provision-with-micromamba@main
        #with:
          #environment-file: environment.yml
          #environment-name: convml_tt

#      - name: Setup conda
#        uses: s-weigand/setup-conda@v1
#        with:
#          update-conda: true
#          python-version: ${{ matrix.python-version }}
#          conda-channels: anaconda, conda-forge
#      - run: conda --version
#      - name: Add conda to system path
#        run: |
#          # $CONDA is an environment variable pointing to the root of the miniconda directory
#          echo $CONDA/bin >> $GITHUB_PATH
#      - name: Install dependencies
#        run: |
#          conda env update --file environment.yml --name fcfa-swift

#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v2
      - name: Install test packages
        shell: bash -l {0}
        run: |
          pip install pytest nbval
      - name: which python
        shell: bash -l {0}
        run: |
          which python
      - name: Download test data
        run: |
          bash binder/postBuild
      - name: git info
        run: |
          git log --name-only -1 | cat -
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest --nbval
